// Auto-generated by scripts/build-builtin-keyring.ts.
// Do not edit by hand — regenerate after curating
// data/keyring/publishers.v1.json. CI verifies this file
// matches the JSON via `git diff --exit-code`.

export const BUILTIN_KEYRING_HASH = "sha256:21b1783e4550865046fea0d66d825774deb11665960f9eee6519c44588782833";
