#!/usr/bin/env bun
// Regenerate src/setup/builtinKeyringHash.ts from
// data/keyring/publishers.v1.json.
//
// The hash is sha256 over the raw committed bytes of the JSON. It
// gets baked into source so that a packager swapping the JSON post-
// install (or an auto-update fetching tampered bytes) can be caught
// at load: see src/setup/builtinKeyring.ts:loadBuiltinKeyring. Closes
// Batch N S306 (catalog had no integrity check; same risk applies to
// the keyring with higher blast radius).
//
// Idempotent. CI invokes it via:
//   bun run scripts/build-builtin-keyring.ts \
//     && git diff --exit-code src/setup/builtinKeyringHash.ts
// — non-zero diff means the JSON changed without the hash being
// regenerated, which the gate (mismatch → BUILTIN_KEYRING_HASH_MISMATCH)
// would expose at runtime anyway. Catching it in CI keeps the failure
// mode at PR-review-time instead of installer-time.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { hashBytes } from "../src/setup/canonical.ts";

const ROOT = resolve(import.meta.dir, "..");
const JSON_PATH = resolve(ROOT, "data/keyring/publishers.v1.json");
const TS_PATH = resolve(ROOT, "src/setup/builtinKeyringHash.ts");

const bytes = readFileSync(JSON_PATH);
const hash = hashBytes(bytes);

const banner = "// Auto-generated by scripts/build-builtin-keyring.ts.\n"
    + "// Do not edit by hand — regenerate after curating\n"
    + "// data/keyring/publishers.v1.json. CI verifies this file\n"
    + "// matches the JSON via `git diff --exit-code`.\n";

const body = `export const BUILTIN_KEYRING_HASH = ${JSON.stringify(hash)};\n`;

writeFileSync(TS_PATH, banner + "\n" + body);
process.stdout.write(`✓ wrote ${TS_PATH}\n`);
process.stdout.write(`  hash: ${hash}\n`);
